### ISSUE TITLE
Guild-Removing option for siteadmins

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#389]
**Is your feature request related to a problem? Please describe.**
A siteadmin should have full control over MASZ, so he should also be able to unregister an registered guild, regardless of having admin permissions for that guild or not.

**Describe the solution you'd like**
Siteadmins should have a delete button next to all guilds to unregister those guilds (similar to the delete button of guild admins)

**Additional context**
![mCLq7mr 1](https://user-images.githubusercontent.com/68478616/130360253-247e4aea-7b0a-415e-b57a-d0df13414e60.png)

**Comment by zaanposni** [comment]
Thanks for your report @FlixProd 

You are right, siteadmins should be able to edit/delete guilds all the time.
These buttons are missing right now but are easy to add, I will make the relevant changes asap.

**Comment by zaanposni** [comment]
Hey @FlixProd 
i have merged the requried changes into the master branch, feel free to update your instance and try it out :)
