### ISSUE TITLE
add title and description field to modcase commands

### ISSUE THREAD

**Issue by Bricksmaster** [zaanposni/discord-masz#405]
It would be nice if the slash commands "warn", "mute", "kick", "ban" and "tempmute" would support entering a title and a description and not like currently only a reason which is used for title and subscription.
![unknown](https://user-images.githubusercontent.com/47327755/131987655-1e84b56e-da79-4fcd-a8f2-dc7b2fd4db90.png)

**Comment by zaanposni** [comment]
Will be done in `v2` with the new command structure -> #404

**Comment by zaanposni** [comment]
Will be supported with the new `punish` command in `v2`.
