### ISSUE TITLE
Unix-Timestamps

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#414]
The Discord bot should use the built-in Unix timestamps for dates instead of the normal strings. This would make it easier to understand the data, since the timestamps automatically adjust to the user's timezone, and it would be possible to create time spans (X days ago).

### Links:
Discord-Docs: https://discord.com/developers/docs/reference#message-formatting-formats

![image](https://user-images.githubusercontent.com/68478616/134343965-4db3d535-3fae-404b-a76a-ccf3e5c48575.png)

### Examples:
![waRUcuw 1](https://user-images.githubusercontent.com/68478616/134344757-873a5ef9-163c-48a9-8fda-b5b78b08529a.gif)
![abc](https://i.imgur.com/tj8DDhI.png)

**Comment by zaanposni** [comment]
thank you very much @FlixProd 
I did not know about that feature.

I will use it in the upcoming `v2` release.

**Comment by zaanposni** [comment]
I have implemented this in the new `v2` version. Closing this issue for clarity and planning of the new release.
