### ISSUE TITLE
Adding Reasoning for server audit logs.

### ISSUE THREAD

**Issue by TrissieTheHusky** [zaanposni/discord-masz#469]
**Is your feature request related to a problem? Please describe.**
I really think the bot should add reasons when it bans or kicks someone with the moderator making the punishment so it doesn’t cause confusion if something happens to the bot. For the server audit logs. As of now it doesn’t specify reasons in audit logs.

**Describe the solution you'd like**
Allow an option to choose reasoning added or not. Something to set the reasons for banning in the audit logs.

**Describe alternatives you've considered**
I’m not sure some way to implement reasoning to bans in the audits.

**Additional context**

**Comment by zaanposni** [comment]
Are you refering to discords audit log or MASZ' audit log?
![grafik](https://user-images.githubusercontent.com/24491035/146652473-e8595a4a-c9c2-4263-a7b0-0d0dfb676925.png)
![grafik](https://user-images.githubusercontent.com/24491035/146652466-0aa0a6a6-f724-4734-bbe3-f9aa10132a6a.png)

Anyway I like the idea and will look into it.
Maybe we can use the modcase title for this?

https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-entry-structure

It seems like the limit is 512 chars, so we might have to cut it if it exceeds those (unlikely).

**Comment by TrissieTheHusky** [comment]
The discord reasoning for banning and kicking. Aswell as many other things. So discord audit log.

**Comment by zaanposni** [comment]
Alright, will be included in the next release 👍 
We are currently rewriting MASZ' backend, so it might take a few days.

**Comment by TrissieTheHusky** [comment]
Nice, I’m glad that I was able to help address something that could be useful and implemented.

**Comment by FeroxFoxxo** [comment]
I believe this should already be included with the rewrite branch, closing :3
