### ISSUE TITLE
Extended /say Feature for MASZ

### ISSUE THREAD

**Issue by Bricksmaster** [zaanposni/discord-masz#479]
Currently with the slash command "/say" it is possible to send Messages via MASZ resp. the MASZ Bot.

This feature can be upgraded with a new feature which makes it possible to send messages via. the MASZ Website. 

The advantage of this feature will be an editor at the website which will offer easier editing and shaping of the messages without messing with Markdown. The editor will either convert the shaped messages into Markdown for Discord or will provide a clear text and markdown editor, where the user can decide what he wants to use.

Additionally, the feature should also include a planning feature which makes it possible to plan a message. That means, that you can choose when and where the messages will be send. This is useful when scheduling messages for seasonal holidays e.g. Christmas.

**Comment by zaanposni** [comment]
![grafik](https://user-images.githubusercontent.com/24491035/147823645-cddb9c22-14d4-4e4a-bf4f-56ade5674fc1.png)

**Comment by zaanposni** [comment]
@Bricksmaster Do you think we need a markdown/embed editor for this as well?
I feel like the current /say command and scheduled message feature is enough.
![grafik](https://user-images.githubusercontent.com/24491035/157253116-eff7c685-f99e-4c09-94d4-5833475303e0.png)

**Comment by Bricksmaster** [comment]
In general, the current feature works well. Markdown should work seamless in Discord therefore an editor should be added. 
I would lower the prio for this feature.

**Comment by zaanposni** [comment]
as all markdown can be used in the current /say command and scheduled message feature, I am closing this issue.
