### ISSUE TITLE
Re-enable audit-log events is not logged correctly

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#482]
When you disable a configured audit log event, and than enable it again, the activation doesn't trigger a log message (first when you edit the config a message is sent)

https://user-images.githubusercontent.com/68478616/147854772-5329901a-ef64-4ef2-b4b5-513c27ac6e4c.mp4

**Comment by zaanposni** [comment]
Problem is that simply clicking the checkbox again doesnt actually reactivate the guild auditlog. 
The previous channel is still displayed although it isnt actually ther,, which causes the confusion here.

I will look into it to correctly clear the displayed roles and channel so it is clear, that you have to select a channel manually again.

**Comment by zaanposni** [comment]
fixed in release branch, will be included in `v2.6.0`
