### ISSUE TITLE
Usermap & Usernote require page refresh

### ISSUE THREAD

**Issue by FeroxFoxxo** [zaanposni/discord-masz#491]
![image](https://user-images.githubusercontent.com/51069105/151933913-8b2afdb5-a42e-4deb-bc1a-60ac8cac5707.png)

**Comment by zaanposni** [comment]
should be just a reset bug, maybe a string or list is not resetted correctly.

**Comment by zaanposni** [comment]
fixed in release 2.7.0 branch
