### ISSUE TITLE
Tab title window replaced with bot's name

### ISSUE THREAD

**Issue by FeroxFoxxo** [zaanposni/discord-masz#492]
Tabs do not currently use the applications name.

![image](https://user-images.githubusercontent.com/51069105/151933987-21fce54c-b5f8-4687-b860-eb4f90cd4a5b.png)

**Comment by zaanposni** [comment]
good idea, as the index.html is not a angular component this needs to be done via a ID. Select the html element and overwrite it if the appsettings loaded

**Comment by zaanposni** [comment]
fixed in release branch v2.7.0
﻿
