### ISSUE TITLE
Improper centering of guild names

### ISSUE THREAD

**Issue by FeroxFoxxo** [zaanposni/discord-masz#493]
![image](https://user-images.githubusercontent.com/51069105/151936081-7ea19125-6165-4bc3-9f70-c91a90674312.png)
![image](https://user-images.githubusercontent.com/51069105/151936127-2dfc1153-11b8-424f-abce-fbd24365ae9e.png)

**Comment by FeroxFoxxo** [comment]
Happens notably when resizing the window, or with longer guild names, like the latter image.

**Comment by zaanposni** [comment]
guild names are just too long, maybe I can make the element expand so longer names will fit, this might break the guild add view where you have a complete list of all guilds though

**Comment by zaanposni** [comment]
I have made the area for text a bit bigger. However, very long guild names will still have to use multiple lines.
-> v2.7.0 release branch
