### ISSUE TITLE
More intuitive ban appeal process

### ISSUE THREAD

**Issue by FeroxFoxxo** [zaanposni/discord-masz#495]
Needs to be discussed further.

Premise: You should be able to *easily* file a ban appeal through the website of MASZ, that gets sent to the moderation team for direct approval. Perhaps through both the website, as a new column in the dashboard, or by using buttons on a appeal message.

- [ ] mail notification system
- [x] add field to guildconfig to allow appeal after x days
- [x] warning in guild dashboard if no appeals configured
- [x] show appeal stats and history in guild dashboard
- [x] add users from modcases and appeals to /member endpoint?

**Comment by FeroxFoxxo** [comment]
![image](https://user-images.githubusercontent.com/51069105/152144541-82f423e8-bd96-4a93-a827-63be615d0400.png)

**Comment by zaanposni** [comment]
![image](https://user-images.githubusercontent.com/24491035/153927880-d2f01e98-c7fe-4221-897f-de3318baa031.png)

**Comment by zaanposni** [comment]
in release branch v2.7.0
