### ISSUE TITLE
Automatic check tool for correct channel mute with mute role

### ISSUE THREAD

**Issue by Bricksmaster** [zaanposni/discord-masz#512]
Currently, especially on large servers with a lot of channels, it easily can happen that a user with a mute role can write in a channel although he is muted.
This happens even after minor changes. Especially on servers with a member role and not using the default everyone role for normal users.

Therefore, MASZ should provide a check tool, run by a slash command, which automatically checks if the mute role works correctly and if not, will show the mods/admins the corresponding channels.

It is important that this feature should provide correct information even with other rules the users could have. Therefore it is important to mention the mute role and the standard user role within the guild settings.

**Comment by zaanposni** [comment]
I think discords feature "View server as role" is sufficient for this problem.
If I would implement this on MASZ it would just be a worse clone of the existing discord feature.
