### ISSUE TITLE
Case file/image upload from the clipboard

### ISSUE THREAD

**Issue by Bricksmaster** [zaanposni/discord-masz#519]
When creating a case, the only way to upload an image or a file is to select it with the “select file” window. Therefore, it is necessary to save every picture on your desktop before uploading it to MASZ.

As this takes extra time and most of this pictures will be deleted from the desktop afterwards, it would be helpful to provide the upload for pictures/files from the clipboard.

Usually, moderators/administrator take their screenshot with third-party software like Lightshot which saves the relevant information within this screenshot. Uploading this picture directly from the clipboard will save time and makes the motivation for providing evidences a bit better.

**Comment by zaanposni** [comment]
Thanks for your idea, I will include this in the upcoming v3 release.

**Comment by zaanposni** [comment]
fixed in v3 branch :eyes:
