### ISSUE TITLE
Permanent delete for cases with admin permission

### ISSUE THREAD

**Issue by Bricksmaster** [zaanposni/discord-masz#520]
Currently permanent deletion is limited to SiteAdmins. To delegate this task to other users, there should be a button at the guild setting (e.g. "Admin can permanently delete cases") which allows the User with Admin permissions to permanent delete cases.

As some guilds might not want this feature, the permission should not be hardcoded to the admin role and only an optional checkbox to activate this.

**Comment by zaanposni** [comment]
admins will be able to instantly delete cases in v3 similiar to siteadmins.

**Comment by zaanposni** [comment]
I will close this issue since it has been fixed on the v3 branch :smile:
