### ISSUE TITLE
Usernotes revamp feature

### ISSUE THREAD

**Issue by UponAnonymous** [zaanposni/discord-masz#522]
The current Usernote feature is really good for staff to log information regarding certain users, but it's not that acceptable to see from Discord.

That is why there could be a way that staff can not only create, edit and delete user notes, but also can be viewed too through the "whois" command.
However, the Whois command will only show the usernotes of the user if it was executed by a staff member or if it was done in an area only visible by staff.

**Comment by zaanposni** [comment]
The whois command is already only executable by staff members.
The whois command already shows usernotes and maps.
Attached is a screenshot from the demo instance as an example 😄 
![](https://media.discordapp.net/attachments/788065275210760232/968750257183817728/unknown.png)
