### ISSUE TITLE
Message page date shows different and also voice channels show in selection.

### ISSUE THREAD

**Issue by UponAnonymous** [zaanposni/discord-masz#528]
**Describe the bug**
When trying to schedule a message from the MASZ website you then get your date changed to something completely different and unusual (see below) and also when looking through the channel list you'll see Voice Channels

**To Reproduce the Date bug**
1. Go to the message page on the MASZ site
2. Click on 'Create new message'
3. Click on the date area and add your desired date

**To Reproduce the Voice Channel bug** (Make sure you have a Voice Channel on the server)
1. Go to the message page on the MASZ site
2. Click on 'Create new message'
3. Click on the 'Channel' dropdown and there you should see the Voice Channel

**Expected behaviour (Date)**
Upon selecting the desired date it should show up as date in the format of 'YYYY-MM-DD'

**Expected behaviour (Voice Channel)**
Voice channels shouldn't show up on the dropdown unless MASZ supports the new 'Chat in Voice' feature

**Screenshots**
Date Bug:
![image](https://user-images.githubusercontent.com/27465814/172042197-17648aa0-6dd8-451d-abee-47ef065a8edd.png)
Voice Channel Bug:
![image](https://user-images.githubusercontent.com/27465814/172042304-53ec588d-72fc-46c1-95ef-d70cd519a95f.png)

**Comment by zaanposni** [comment]
fixed in 3.0.2
