### ISSUE TITLE
Confusing text on the dashboard if there are no cases yet

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#529]
If a guild does not have any cases yet, the widgets on the dashboard show the error message `This is not the widget you are looking for`. This is a bit confusing because it doesn't really describe the problem. The message `No cases have been created yet` would be better and clearer. 
![image](https://user-images.githubusercontent.com/68478616/172365679-f0286833-23a9-482c-a072-bdded3ebf00d.png)

**Comment by UponAnonymous** [comment]
I think the best thing that could be done is to have something like this, as at least it keeps the Star Wars reference there.

![image](https://user-images.githubusercontent.com/27465814/172367426-b3d62bd2-e307-4ccf-a341-1e4f5017ca54.png)

**Comment by zaanposni** [comment]
I like @UponAnonymous idea, we can definitely do that.
Its actually pretty simple, if someone wants to work on it, let me know and I will guide you :sweat_smile: 

![image](https://user-images.githubusercontent.com/24491035/172372985-79ddf900-d0af-410b-af7d-5517030b75a1.png)

**Comment by zaanposni** [comment]
Fixed in v3.1.0 release branch.

I went for a slightly different solution since mine is more in line with the carbon design and I want the v3 frontend to be consistent with that.
![image](https://user-images.githubusercontent.com/24491035/173182835-0656f110-ca88-43d9-b3a4-8c131e842ae8.png)
