### ISSUE TITLE
detect insults or forbidden content in a userprofile

### ISSUE THREAD

**Issue by zaanposni** [zaanposni/discord-masz#532]
check `about me`, `status`, `nickname` and `username` to check for insults or invite links or similiar and report them to the moderator webhook, similiar to the zalgo feature

**Comment by FeroxFoxxo** [comment]
JFTR, I believe a user's about me is not exposed, due to data privacy issues. Unsure of statuses either. Nicknames and usernames should be achievable though.

**Comment by zaanposni** [comment]
closed. not possible as ferox explained
