### ISSUE TITLE
Add the current guild to the upper bar

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#540]
Currently, it's not really clear, in what guild you are currently in. This is confusing and maybe also dangerous, e.g. if you change the automod settings for the wrong guild. 
To solve this, it would be helpful, if the icon and the name of the current guild is displayed on the upper bar.

#### Maybe something like this (photoshopped):
![image](https://user-images.githubusercontent.com/68478616/184703404-0ba0d067-cce2-4b56-a095-3e7fbd55781c.png)

**Comment by zaanposni** [comment]
fixed in release branch v3.1.3
