### ISSUE TITLE
Filter and/or search when adding new guilds

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#547]
It would be very helpful, if we could search the guilds on the [page for registering new guilds](https://demomasz.zaanposni.com/guilds/new). Another option (which I prefer tbh) would be to add a filter that shows all guilds where the user has the necessary permissions (`manage_guild`) to add a bot on the top of the page. 

The current system works, but especially for users with many guilds (>80) it's difficult to find the right guild.

**Comment by zaanposni** [comment]
fixed in v3.3.0 release branch
