### ISSUE TITLE
Anti-Phishing / Anti-scam Automod

### ISSUE THREAD

**Issue by UponAnonymous** [zaanposni/discord-masz#557]
Currently with MASZ there's no way besides the "Custom Wordfilter" automod to stop people having scam links sent in their server.
Anti-Phishing / Anti-Scam auto mod would be a good edition to MASZ as it'll help protect the server by removing one of the most common threats for any server.

Luckily there's an [NPM Package](https://www.npmjs.com/package/stop-discord-phishing) that can be used to help crack down on these type of scams within servers using MASZ.

**Comment by zaanposni** [comment]
will be included in v3.3.0

**Comment by zaanposni** [comment]
done in release branch v3.3.0

**Comment by zaanposni** [comment]
**Limited phishing list | Low memory mode** :fishing_pole_and_fish: 

Use the following environment variable in your `.env` file to load a minimal list for phishing automod.

`ENABLE_LOW_MEMORY_PHISHING_LIST=true`
