### ISSUE TITLE
Server Backup Feature

### ISSUE THREAD

**Issue by UponAnonymous** [zaanposni/discord-masz#558]
_Now before I even start my suggestion, Zaanposni kept telling me not to post this. But here we are >:)_

Currently, on MASZ the focus is protecting users and the server from trolls, but there's no way to undo something serious like a user or in worse cases a staff member nuking a server and removing everything.

If MASZ had something like a backup feature that would save everything in your server (channels, roles, server settings, messages, bans, nicknames, role assignments etc.) just in case something like this were to happen, the guild owner could just go to the dashboard and roll back the server as if nothing bad happened (obviously there's no way to get users back if they got kicked unless something could be added to notify them in future)

Another thing that could be done is an auto-backup option where the guild owner can decide how frequent the backups should be (hourly, daily, weekly, monthly). While the bot owner can decide how many backups can be made (per server) before they get deleted to save storage.

**Comment by zaanposni** [comment]
As previously stated this isnt something that I plan for MASZ.
I think it neither fits into the moderation scope of MASZ nor would it provide actual benefits, since there are already mature bots available for this use-case.
