### ISSUE TITLE
save messages as verified evidence in modcases

### ISSUE THREAD

**Issue by zaanposni** [zaanposni/discord-masz#562]
could be implemented similar to linked cases. verifies the authenticity of messages related to a modcase

idea from: #555

**Comment by zaanposni** [comment]
I like the way sapphire displays message evidence, maybe we could implement something similar
![grafik](https://user-images.githubusercontent.com/24491035/207860726-75d203c5-df62-41e5-b222-6978fbc7e7da.png)

**Comment by Simply-Cods** [comment]
Anyone working on this?

**Comment by zaanposni** [comment]
Nope, you are good to go. Let me know if you have any questions :) @Simply-Cods

**Comment by zaanposni** [comment]
- new table/view with saved/verified messages
- can be added via directlink in the dashbaord or via right click (as you mentioned)
  in the dashboard you would have to paste a message link that the backend parses via regex
- can be linked to a modcase during creation or via the case view
- automatically linked to an automod
- not shown in the webhook embeds, that way probitied content is not logged in the public channel

**Comment by zaanposni** [comment]
closing this since cods already provided this feature in their pull request
