### ISSUE TITLE
Suggestion: To be able to customise the status of the bot.

### ISSUE THREAD

**Issue by Sai-Tamazaki** [zaanposni/discord-masz#563]
I would like to see the ability to customise the status message of the bot, perhaps through the front-end control panel interface for the website, for site administrators. Thank you kindly.

**Comment by zaanposni** [comment]
done in release branch for v3.3.0

thanks for your suggestion

**Comment by zaanposni** [comment]
**Custom status** :robot: 

In version 3.3.0 or later you can use the following environment variable to set a custom status for your discord bot:
Edit the `.env` file and insert the following:

- `DISCORD_BOT_STATUS=none` for no status
- `DISCORD_BOT_STATUS=test` for status "test"
- remove the env var or set it to an empty string to display the default status.
