### ISSUE TITLE
Mentioning of channels/users in case description of slash commands

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#566]
When creating a case using a slash command (`/warn`, `/mute`, ...) you can mention a channel or a user in the description. Generally this is very useful to describe the details of the case, especially for complex situations. Unfortunately, the dashboard view of the case just displays the raw content (`<@1234>`, `<#1234>`) and also thinks that the channel id refers to a case and trys to link it. 
To fix this, MASZ should replace the mentions of the provided description with the name of the user/channel (`@Sapphire`, `#chat`).

![image](https://user-images.githubusercontent.com/68478616/209483209-7e16d725-a17e-42c5-8d47-ad650aaca2db.png)
![image](https://user-images.githubusercontent.com/68478616/209483224-ae5cac87-dcae-4465-aab7-7abf5b117a88.png)

**Comment by FlixProd** [comment]
Same problem with titles

![image](https://user-images.githubusercontent.com/68478616/209483313-188fdd55-1b1b-49d7-b4f3-2bbf177e7caf.png)

**Comment by zaanposni** [comment]
@FlixProd 
Is this design okay or would you like something more distinguished like discord uses?
![image](https://user-images.githubusercontent.com/24491035/209514967-a54067a9-4c3d-49b9-8afd-ec9d576eb41e.png)

**Comment by zaanposni** [comment]
Titles are reserved for string only, as they are used at many places, there is no good way to support replacing and styling there.

**Comment by FlixProd** [comment]
> Is this design okay or would you like something more distinguished like discord uses?

No, that's already more than I wanted! Great, thank you! 🚀

**Comment by zaanposni** [comment]
fixed in release branch
