### ISSUE TITLE
remove old dotnet build from github actions

### ISSUE THREAD

**Issue by zaanposni** [zaanposni/discord-masz#575]
Is no longer needed since the docker build is checked as well.
Furthermore, it currently fails because of a old ubuntu tag.

**Comment by mtsalt** [comment]
Hello @zaanposni 

I understand that the backend/Dockerfile plays a role in .github/workflows/dotnet_build.yml
So I am thinking of deleting dotnet_build.yml.

If my understanding is correct, please assign me this issue.

**Comment by zaanposni** [comment]
Hi @mtsalt 

The Dockerfile is not really needed in that CI file. 
But deleting the mentioned file should solve this issue.

Feel free to go ahead

**Comment by mtsalt** [comment]
@zaanposni 

Thank you for your assignment. I deleted the file.

**Comment by zaanposni** [comment]
Thanks for your contribution @mtsalt
